CC = gcc

build: p1 p2 p3 p4 best
p1: p1.c
	gcc -o p1 p1.c
p2: p2.c
	gcc -o p2 p2.c
p3: p3.c
	gcc -o p3 p3.c
p4: p4.c
	gcc -o p3 p4.c
best: best.c
	gcc -o best best.c
run-p1:
	gcc -o p1 p1.c
	./p1
run-p2:
	gcc -o p2 p2.c
	./p2
run-p3:
	gcc -o p3 p3.c
	./p3
run-p4:
	gcc -o p4 p4.c
	./p4
run-best:
	gcc -o best best.c
	./best
  clean: 
	  rm -f  p1 p2 p3 p4 best


